
name: build-site

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
      
      - name: update submodule
        run : |
          git submodule update --init
      
      - name: install emcc
        run : |
          git pull
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.
      
      - name: Get emcc
        uses: emscripten-core/setup-emsdk@v15

      - name: Build wasm worlet
        run : |
          cd voice
          make

      - name: Build site
        run: | 
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .